# Perfil de TESTES (H2 em memória)
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

# Configurações comuns a todos os perfis
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info # depois podemos abrir mais
  endpoint:
    health:
      show-details: when_authorized