spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gestaoalunos_dev}
    username: ${SPRING_DATASOURCE_USERNAME:gestao}
    password: ${SPRING_DATASOURCE_PASSWORD:gestao}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: 8080

app:
  jwt:
    secret: ${APP_JWT_SECRET:uma-chave-secreta-bem-grande-e-dificil}
    expiration: ${APP_JWT_EXPIRATION:3600000}